### ISSUE TITLE
cannot run: java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by lilydjwg** [Rossi1337/pdf_vole#2]
```
java.lang.IllegalAccessError: class org.jdesktop.application.Application (in unnamed module @0x46d21ee0) cannot access class sun.awt.AppContext (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x46d21ee0
	at org.jdesktop.application.Application.launch(Application.java:182)
	at org.jdesktop.application.Application$1.run(Application.java:169)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

My java is version 17.

**Comment by evantill** [comment]
you need to add this export module argument to your command line : `--add-exports=java.desktop/sun.awt=ALL-UNNAMED` (before the `-jar`argument).

### Example  : 

```shell
java --add-exports=java.desktop/sun.awt=ALL-UNNAMED -jar pdfvole_20210711.jar
```

**Comment by lilydjwg** [comment]
Thanks, it worked!
